version: "3.9"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: bellevitesse
      MYSQL_USER: admin
      MYSQL_PASSWORD: PYpD3JH3TK
      MYSQL_ROOT_PASSWORD: PYpD3JH3TK
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - core_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  nocodb:
    image: nocodb/nocodb
    environment:
      NC_DB: mysql://admin:PYpD3JH3TK@mysql:3306/bellevitesse
    labels:
      - traefik.enable=true
      - traefik.http.routers.nocodb.rule=Host(`db.bellevitesse.com`)
      - traefik.http.routers.nocodb.entrypoints=websecure
      - traefik.http.routers.nocodb.tls.certresolver=le
    networks:
      - core_net
      - web
    depends_on:
      mysql:
        condition: service_healthy

  flask:
    build: ./flask
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql+pymysql://admin:PYpD3JH3TK@mysql:3306/bellevitesse
    volumes:
      - ./flask/static/images/airtable:/app/static/images/airtable
    labels:
      - traefik.enable=true
      - traefik.http.routers.flask.rule=Host(`bellevitesse.com`)
      - traefik.http.routers.flask.entrypoints=websecure
      - traefik.http.routers.flask.tls.certresolver=le
    networks:
      - core_net
      - web
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysqldata:

networks:
  core_net:
  web:
    external: true
