services:
  flask_app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: bv_flask_app
    restart: always
    env_file:
      - ../.env
    environment:
      - MYSQL_HOST=bv_mysql 
    volumes:
      - ../static/images/airtable:/app/static/images/airtable
    networks:
      - bv_network
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bv_app.rule=Host(`www.bellevitesse.com`,`bellevitesse.com`)"
      - "traefik.http.routers.bv_app.entrypoints=websecure"
      - "traefik.http.routers.bv_app.tls.certresolver=letsencrypt"
      - "traefik.http.services.bv_app.loadbalancer.server.port=5001"
    ports:
      - "5001:5001"

networks:
  bv_network:
    name: bv_network
    external: true
  traefik_default:
    external: true
