services:
  mysql:
    image: mysql:8.0
    container_name: bv_mysql
    restart: always
    env_file:
      - ../.env
    volumes:
      - bv_db_data:/var/lib/mysql
    networks:
      - bv_network

networks:
  bv_network:
    name: bv_network
    external: true

volumes:
  bv_db_data:
